Roll-up of SVN hotplug branch at most recent revision (r1677), based at the same point in the master revision history as it was originally applied.

diff --git a/install-sh b/install-sh
--- a/install-sh
+++ b/install-sh
@@ -129,7 +129,7 @@ Environment variables override the default commands:
 "
 
 while test $# -ne 0; do
-  case $1 in
+    case $1 in
     -c) ;;
 
     -C) copy_on_change=true;;
@@ -150,7 +150,7 @@ while test $# -ne 0; do
 	esac
 	shift;;
 
-    -o) chowncmd="$chownprog $2"
+	-o) chowncmd="$chownprog $2"
 	shift;;
 
     -s) stripcmd=$stripprog;;
@@ -170,7 +170,7 @@ while test $# -ne 0; do
 
     *)  break;;
   esac
-  shift
+	    shift
 done
 
 if test $# -ne 0 && test -z "$dir_arg$dst_arg"; then
@@ -183,17 +183,17 @@ if test $# -ne 0 && test -z "$dir_arg$dst_arg"; then
       # $@ is not empty: it contains at least $arg.
       set fnord "$@" "$dst_arg"
       shift # fnord
-    fi
+	    fi
     shift # arg
     dst_arg=$arg
-  done
+done
 fi
 
 if test $# -eq 0; then
   if test -z "$dir_arg"; then
     echo "$0: no input file specified." >&2
-    exit 1
-  fi
+	exit 1
+fi
   # It's OK to call `install-sh -d' without argument.
   # This can happen when creating conditional directories.
   exit 0
@@ -201,7 +201,7 @@ fi
 
 if test -z "$dir_arg"; then
   trap '(exit $?); exit' 1 2 13 15
-
+	
   # Set umask so as not to create temps with too-generous modes.
   # However, 'strip' requires both read and write access to temps.
   case $mode in
@@ -212,14 +212,14 @@ if test -z "$dir_arg"; then
     *[0-7])
       if test -z "$stripcmd"; then
 	u_plus_rw=
-      else
+	else
 	u_plus_rw='% 200'
-      fi
+	fi
       cp_umask=`expr '(' 777 - $mode % 1000 ')' $u_plus_rw`;;
     *)
       if test -z "$stripcmd"; then
 	u_plus_rw=
-      else
+else
 	u_plus_rw=,u+rw
       fi
       cp_umask=$mode$u_plus_rw;;
@@ -241,17 +241,17 @@ do
   else
 
     # Waiting for this to be detected by the "$cpprog $src $dsttmp" command
-    # might cause directories to be created, which would be especially bad
-    # if $src (and thus $dsttmp) contains '*'.
+# might cause directories to be created, which would be especially bad 
+# if $src (and thus $dsttmp) contains '*'.
     if test ! -f "$src" && test ! -d "$src"; then
       echo "$0: $src does not exist." >&2
-      exit 1
-    fi
-
+		exit 1
+	fi
+	
     if test -z "$dst_arg"; then
       echo "$0: no destination specified." >&2
-      exit 1
-    fi
+		exit 1
+	fi
 
     dst=$dst_arg
     # Protect names starting with `-'.
@@ -269,7 +269,7 @@ do
       dstdir=$dst
       dst=$dstdir/`basename "$src"`
       dstdir_status=0
-    else
+	else
       # Prefer dirname, but fall back on a substitute if dirname fails.
       dstdir=`
 	(dirname "$dst") 2>/dev/null ||
@@ -299,8 +299,8 @@ do
 
       test -d "$dstdir"
       dstdir_status=$?
-    fi
-  fi
+	fi
+fi
 
   obsolete_mkdir_used=false
 
@@ -343,7 +343,7 @@ do
 
 	    if (umask $mkdir_umask &&
 		exec $mkdirprog $mkdir_mode -p -- "$tmpdir/d") >/dev/null 2>&1
-	    then
+        then
 	      if test -z "$dir_arg" || {
 		   # Check for POSIX incompatibilities with -m.
 		   # HP-UX 11.23 and IRIX 6.5 mkdir -m -p sets group- or
@@ -363,10 +363,10 @@ do
 	      then posix_mkdir=:
 	      fi
 	      rmdir "$tmpdir/d" "$tmpdir"
-	    else
+	else
 	      # Remove any dirs left behind by ancient mkdir implementations.
 	      rmdir ./$mkdir_mode ./-p ./-- 2>/dev/null
-	    fi
+	fi
 	    trap '' 0;;
 	esac;;
     esac
@@ -420,7 +420,7 @@ do
 	      *) qprefix=$prefix;;
 	    esac
 	    prefixes="$prefixes '$qprefix'"
-	  fi
+	fi
 	fi
 	prefix=$prefix/
       done
@@ -454,8 +454,8 @@ do
 
     # and set any options; do chmod last to preserve setuid bits.
     #
-    # If any of these fail, we abort the whole thing.  If we want to
-    # ignore errors from any of these, just make sure not to ignore
+# If any of these fail, we abort the whole thing.  If we want to
+# ignore errors from any of these, just make sure not to ignore
     # errors from the above "$doit $cpprog $src $dsttmp" command.
     #
     { test -z "$chowncmd" || $doit $chowncmd "$dsttmp"; } &&
